spring:
  cloud:
    gateway:
      routes:
        -
          id: users-status-check
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/users/status/check
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>/?.*), /$\{segment}
            - AuthorizationHeaderFilter
        -
          id: users-ws
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>/?.*), /$\{segment}
        -
          id: users-ws-login
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/users/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>/?.*), /$\{segment}
        -
          id: users-ws-get-update-delete
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/users/**
            - Method=GET, UPDATE, DELETE
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>/?.*), /$\{segment}
            - AuthorizationHeaderFilter

