spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server.port: 8011
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    prefer-ip-address: true
info:
  app:
    name: '@project.name@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
  service:
    name: ${spring.application.name}