spring:
  cloud:
    gateway:
      routes:
        -
          id: users-status-check
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/users/status/check
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>/?.*), /$\{segment}
            - AuthorizationHeaderFilter

