spring:
  profiles:
    include: routing-using-yaml
  #all defaults - no need to set up
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    enabled: true
  sleuth:
    reactor:
      instrumentation-type: decorate_on_each # Less performing and deprecated. Will be removed in Sleuth 4.0.0

server.port: 8011
eureka:
  client:
    service-url:
      defaultZone: http://art:123@localhost:8010/eureka
  instance:
    prefer-ip-address: true
info:
  app:
    name: '@project.name@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
  service:
    name: ${spring.application.name}

token:
  secret: blablabla
logging:
  level:
    net.shyshkin: debug

management:
  trace:
    http:
      enabled: true #default value
  endpoint:
    gateway:
      enabled: true #default value
  endpoints:
    web:
      exposure:
        include: beans,health,info,gateway,httptrace

