spring:
  application:
    name: account-management-ws
  #all defaults - no need to set up
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0 #100% of info

server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

info:
  app:
    name: '@project.name@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
  service:
    name: ${spring.application.name}
