version: '3.8'

services:

#  docker run --name photo-app-api -e MYSQL_RANDOM_ROOT_PASSWORD=yes -e MYSQL_USER=photo_app_user -e MYSQL_PASSWORD=photo_app_password -e MYSQL_DATABASE=photo_app_db -v photo-app-volume:/var/lib/mysql -p 23306:3306 -d mysql:8.0.23
  mysql:
    image: mysql:8.0.23
    ports: ["23306:3306"]
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: photo_app_user
      MYSQL_PASSWORD: photo_app_password
      MYSQL_DATABASE: photo_app_db
    volumes:
      - photo-app-volume:/var/lib/mysql


#  docker run -d --hostname my-rabbit --name some-rabbit -p 15672:15672 -p 5672:5672 rabbitmq:3-management
  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
    hostname: my-rabbit


  #  docker run -d -p 9411:9411 openzipkin/zipkin
  zipkin:
    image: openzipkin/zipkin
    ports: ["9411:9411"]

  config-server:
    image: artarkatesoft/photo-app-api-config-server
    ports: ["8012:8012"]
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: ${SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD}
    depends_on:
      - rabbit-mq

  discovery-service:
    image: artarkatesoft/photo-app-discovery-service
    ports: ["8010:8010"]
    restart: on-failure
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8012
    depends_on:
      config-server:
        condition: service_healthy

  api-gateway:
    image: artarkatesoft/photo-app-api-gateway
    ports: ["8011:8011"]
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8012
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
      SPRING_PROFILES_ACTIVE: asymmetric
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      zipkin:
        condition: service_healthy

  albums-ws:
    image: artarkatesoft/photo-app-api-albums
    ports: ["8989:8989"]
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8012
      SERVER_PORT: 8989
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
    volumes:
      - type: bind
        source: 'C:\Users\Admin\IdeaProjects\Study\SergeyKargopolov\MicroservicesCourse\art-kargopolov-microservices\logs'
        target: /application/logs/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/actuator/health"]
      interval: 20s
      timeout: 2s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      zipkin:
        condition: service_healthy

  users-ws:
    image: artarkatesoft/photo-app-api-users
    ports: ["8999:8999"]
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8012
      SERVER_PORT: 8999
      SPRING_PROFILES_ACTIVE: mysql,asymmetric,compose
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
      logging.level.net.shyshkin: debug
      DEBUG: 'true'
    volumes:
      - type: bind
        source: 'C:\Users\Admin\IdeaProjects\Study\SergeyKargopolov\MicroservicesCourse\art-kargopolov-microservices\logs'
        target: /application/logs/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8999/actuator/health"]
      interval: 20s
      timeout: 2s
      retries: 5
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      zipkin:
        condition: service_healthy

volumes:
  photo-app-volume:
