gateway.ip: 192.168.99.1
token:
  expiration_time: 86400000
  secret: modifiedTokenSecretFromNativeRepository1
login.url.path: /users/login

net:
  shyshkin:
    study:
      photoapp:
        api:
          settings:
            description: 'Settings from local repo application yaml'

