spring:
  datasource:
    url: jdbc:mysql://localhost:23306/photo_app_db?serverTimezone=UTC
    username: photo_app_user
    password: photo_app_password
    driver-class-name: com.mysql.cj.jdbc.Driver
net:
  shyshkin:
    study:
      photoapp:
        api:
          settings:
            description: 'Settings from local repository MySQL profile (users-ws-mysql.yaml)'