spring.application.name: config-server
server.port: 8012
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/artshishkin/art-kargopolov-microservices-photo-app-repository
          username: artshishkin
          password: 'PasswordInEnvironmentVariable(or Token - better)'
          clone-on-start: true
          default-label: main
#all defaults - no need to set up
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: 'health, info, bus-refresh'
logging:
  level:
    org.springframework.cloud: debug
    org.springframework.web: debug