spring:
#all defaults - no need to set up
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: 'health, info, bus-refresh'
logging:
  level:
    org.springframework.cloud: debug
    org.springframework.web: debug

---
spring:
  config:
    activate:
      on-profile: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/artshishkin/art-kargopolov-microservices-photo-app-repository
          username: artshishkin
          password: ${docker-secret-git-token} #'PasswordInEnvironmentVariable(or Token - better)'
          clone-on-start: true
          default-label: main

---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - 'file:///${user.home}\IdeaProjects\Study\SergeyKargopolov\MicroservicesCourse\art-kargopolov-microservices\photo-app-api-config-native-repo\'
#            - 'file:///C:\Users\Admin\IdeaProjects\Study\SergeyKargopolov\MicroservicesCourse\art-kargopolov-microservices\photo-app-api-config-native-repo\'

