spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  #all defaults - no need to set up
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0 #100% of info
server.port: ${PORT:0}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
info:
  app:
    name: '@project.name@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
  service:
    name: ${spring.application.name}
    settings: ${net.shyshkin.study.photoapp.api.settings.description}
gateway.ip: 192.168.99.1
token:
  expiration_time: 864000000
  secret: blablabla
login.url.path: /users/login

management:
  endpoints:
    web:
      exposure:
        include: '*'

net:
  shyshkin:
    study:
      photoapp:
        api:
          settings:
            description: 'Settings from internal application yaml'
logging:
  level:
    net.shyshkin.study.photoapp.api.users.services: debug
feign:
  circuitbreaker:
    enabled: true
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:23306/photo_app_db?serverTimezone=UTC
    username: photo_app_user
#    password: '{cipher}550a97f979335f7b2b42d63218f46e3f290f098984b7bd1a2802f18099608f47d94612935859c70e17effa6f08262cdf'
    driver-class-name: com.mysql.cj.jdbc.Driver