spring:
  application:
    name: users-ws
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
server.port: ${PORT:0}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
info:
  app:
    name: '@project.name@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
  service:
    name: ${spring.application.name}
gateway.ip: 192.168.99.1
token:
  expiration_time: 864000000
  secret: blablabla
